/**:
  ros__parameters:
    mujoco_plugins:
      mujoco_3d_lidar_plugin:
        type: "mujoco_ros2_control_plugins/Mujoco3dLidarPlugin"
        lidar2d_0:
          frame_name: "lidar2d_0_laser"
          topic: "/lidar2d_0_laser/scan"
      mujoco_camera_plugin:
        type: "mujoco_ros2_control_plugins/CameraPlugin"
        camera_publish_rate: 2.0
        # These are republished by the mock polled camera, so we suffix these topics
        # with `_` to mark them as such.
        $(var tf_prefix)left_wrist_mounted_camera:
          frame_name: $(var tf_prefix)left_wrist_mounted_camera_color_optical_frame
          info_topic: /$(var tf_prefix)left_wrist_mounted_camera_/color/camera_info
          image_topic: /$(var tf_prefix)left_wrist_mounted_camera_/color/image_raw
          depth_topic: /$(var tf_prefix)left_wrist_mounted_camera_/aligned_depth_to_color/image_raw
        $(var tf_prefix)right_wrist_mounted_camera:
          frame_name: $(var tf_prefix)right_wrist_mounted_camera_color_optical_frame
          info_topic: /$(var tf_prefix)right_wrist_mounted_camera_/color/camera_info
          image_topic: /$(var tf_prefix)right_wrist_mounted_camera_/color/image_raw
          depth_topic: /$(var tf_prefix)right_wrist_mounted_camera_/aligned_depth_to_color/image_raw
