/**:
  controller_manager:
    ros__parameters:
      update_rate: 500

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster


  joint_state_broadcaster:
    ros__parameters:
      # We set joint names explicitly to prevent joint state values for
      # the rails joints, as we want to use the existing localization stack
      # even when running on a magic carpet.
      joints:
        # Phoebe right side
        - $(var tf_prefix)right_ewellix_lift_lower_to_higher
        - $(var tf_prefix)right_ur_arm_shoulder_pan_joint
        - $(var tf_prefix)right_ur_arm_shoulder_lift_joint
        - $(var tf_prefix)right_ur_arm_elbow_joint
        - $(var tf_prefix)right_ur_arm_wrist_1_joint
        - $(var tf_prefix)right_ur_arm_wrist_2_joint
        - $(var tf_prefix)right_ur_arm_wrist_3_joint
        - $(var tf_prefix)right_finger_1_joint

        # Phoebe left side
        - $(var tf_prefix)left_ewellix_lift_lower_to_higher
        - $(var tf_prefix)left_ur_arm_shoulder_pan_joint
        - $(var tf_prefix)left_ur_arm_shoulder_lift_joint
        - $(var tf_prefix)left_ur_arm_elbow_joint
        - $(var tf_prefix)left_ur_arm_wrist_1_joint
        - $(var tf_prefix)left_ur_arm_wrist_2_joint
        - $(var tf_prefix)left_ur_arm_wrist_3_joint
        - $(var tf_prefix)left_finger_1_joint

        - $(var tf_prefix)front_left_wheel_joint
        - $(var tf_prefix)front_right_wheel_joint
        - $(var tf_prefix)rear_left_wheel_joint
        - $(var tf_prefix)rear_right_wheel_joint
      interfaces:
        - position
        - velocity
        - effort
