controller_manager:
  ros__parameters:

    right_lift_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_lift_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

right_lift_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)right_ewellix_lift_lower_to_higher

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false

    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)right_ewellix_lift_lower_to_higher: { trajectory: 0.2, goal: 0.1 }

left_lift_joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)left_ewellix_lift_lower_to_higher

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false

    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      $(var tf_prefix)left_ewellix_lift_lower_to_higher: { trajectory: 0.2, goal: 0.1 }