right_drt_ur_gui:
  ros__parameters:
    dashboard_client_name: "right_dashboard_client"
    freedrive_mode_controller_name: "right_"
    window.name: "PB Remote Commander: Right Arm"
    window.stylesheet: "background-color: #f7937d;"
    robot.name: "PB"
    arm.name: "Right Arm"
    program: "ext_ctrl.urp"
    logo_file_name: 'iMETRO_full.png'
