---
# Configuration for current sensors.
# The approach is taken from https://www.pololu.com/product/5355
# The voltage offset comes from empirically measuring voltage at no-load
# The sensitivity is determined by passing a known current.
# Validity may be set false to indicate a sensor that is present and reported
# by firmware, but is not fully connected, uncalibrated or malfunctioning.
# The number of sensors here should match the number of values reported by the firmware.
sensors:
  - voltage_offset: 1.58900769443616
    name: "Charger"
    description: "Current in from the charger"
    sensitivity: 0.052
    is_valid: true

  - voltage_offset: 1.57526290157567
    name: "Battery"
    description: "Current from the battery"
    sensitivity: 0.013
    is_valid: true

  - voltage_offset: 1.58059249818325
    name: "Inverter"
    description: "Current to the inverter for the onboard PCs and WiFi"
    sensitivity: 0.041
    is_valid: true

  - voltage_offset: 1.55932673164036
    name: "Right Lift"
    description: "Current to the right liftkit"
    sensitivity: 0.094
    is_valid: true

  - voltage_offset: 1.50045582004215
    name: "Whole Robot"
    description: "Main robot current feed"
    sensitivity: 0.039
    is_valid: true

  - voltage_offset: 1.46644462256328
    name: "Left Lift"
    description: "Current to the left liftkit"
    sensitivity: 0.088
    is_valid: true

  - voltage_offset: 1.63564164483029
    name: "MCU"
    description: "Current to the MCU"
    sensitivity: 0.038
    is_valid: true

  - voltage_offset: 1.49719495358674
    name: "Left UR"
    description: "Current to the left UR"
    sensitivity: 0.061
    is_valid: true

  - voltage_offset: 1.49341
    name: "Right UR"
    description: "Current to the right UR"
    sensitivity: 0.061
    is_valid: true

  - voltage_offset: 1.485
    name: "Safety Power"
    description: "Current to the EStop and PLC"
    sensitivity: 0.075
    is_valid: true
