---
sensors:
  - voltage_offset: 1.58900769443616
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.57526290157567
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.58059249818325
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.55932673164036
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.50045582004215
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.46644462256328
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.63564164483029
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.49719495358674
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 1.48355541540229
    sensitivity: 1.0
    is_valid: true

  - voltage_offset: 0.0
    sensitivity: 1.0
    is_valid: false
  