/**:
  puma_control:
    ros__parameters:
      canbus_dev: 'vcan0'
      joint_names: [$(var tf_prefix)front_left_wheel_joint, $(var tf_prefix)front_right_wheel_joint, $(var tf_prefix)rear_left_wheel_joint, $(var tf_prefix)rear_right_wheel_joint]
      joint_can_ids: [5, 4, 2, 3]
      joint_directions: [-1, 1, -1, 1]
      gear_ratio: 34.97
      encoder_cpr: 1024
      gain:
        p: 0.1
        i: 0.01
        d: 0.0
