serial_number: r100-0564
version: 0
system:
  hosts:
    - hostname: cpr-r100-0564
      ip: 192.168.131.1
  ros2:
    namespace: r100_0564
manipulators:
  lifts:
    - model: ewellix
      parent: default_mount
    - model: ewellix
      parent: default_mount
  arms:
    - model: universal_robots
      parent: default_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ur_type: ur5e
      robbot_ip: 192.168.131.42
      headless_mode: false
      kinematics_parameters_file: "$(find ur_description)/config/ur5e/default_kinematics.yaml"
      poses:
        - name: custom
          joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      gripper:
        model: robotiq_2f_140
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        poses:
          - name: custom
            joints: [0.0]
    - model: universal_robots
      parent: default_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ur_type: ur5e
      robbot_ip: 192.168.131.43
      headless_mode: false
      kinematics_parameters_file: "$(find ur_description)/config/ur5e/default_kinematics.yaml"
      poses:
        - name: custom
          joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      gripper:
        model: robotiq_2f_140
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
        poses:
          - name: custom
            joints: [0.0]
sensors:
  lidar2d:
    - model: hokuyo_ust
      urdf_enabled: true
      launch_enabled: true
      parent: base_link
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        urg_node:
          laser_frame_id: lidar2d_0_laser
          ip_address: 192.168.131.20
          ip_port: 10940
          angle_min: -2.356
          angle_max: 2.356
